# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Remix app to Azure Web App - remix-azure-app

on:
  push:
    branches:
      - main

jobs:
  infrastructure: # You can change this name to anything else you wish
    runs-on: ubuntu-latest # This could also be a windows machine e.g windows-latest

    steps:
      - uses: actions/checkout@v2 # This will obtain all the code for you in your repository

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # This is the secret you created in the GitHub repository settings

      - name: Deploy or update infrastructure
        uses: azure/arm-deploy@v1
        with:
          scope: "resource group or subscription scope"
          subscriptionId: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F183081C8B1A477693E58C549FB8B0B2 }} # If you have multiple subscriptions this will switch to the correct subscription for you
          resourceGroupName: ${{ vars.AZURE_SAMPLE_APP_RG }} # This doesn't have to be a variable, you could also hard code this, but ensure you create a variable if you use this approach
          template: ./samples/maira-prediction/infra/github-image-sample-ui.bicep # This is an assumed directory structure ensure you change to the correct directory as well as rename environment to uat or prod etc
          parameters: ./samples/maira-prediction/infra/github-image-sample-ui.bicepparam
          failOnStdErr: false

  # build:
  #   needs: infrastructure # This job depends on the infrastructure job
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Node.js version
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "18.x"

  #     - name: npm install, build, and test
  #       run: |
  #         cd samples/maira-prediction/image-to-findings-sample-app/
  #         npm install
  #         npm run build --if-present
  #         npm run test --if-present

  #     - name: Upload artifact for deployment job
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: sample-app
  #         path: ./samples/maira-prediction/image-to-findings-sample-app/build

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: "Production"
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  #   permissions:
  #     id-token: write #This is required for requesting the JWT

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: sample-app

  #     - name: Login to Azure
  #       uses: azure/login@v1
  #       with:
  #         client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D55C07A849724ACDA32CE31B1BE628E0 }}
  #         tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_73418A7E4D2A49319FB3FD5F0A75D73E }}
  #         subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F183081C8B1A477693E58C549FB8B0B2 }}

  #     - name: Deploy to Azure Web App
  #       uses: azure/webapps-deploy@v2
  #       id: deploy-to-webapp
  #       with:
  #         app-name: "remix-azure-app"
  #         slot-name: "Production"
  #         package: .
